name: Build and deploy ASP.Net Core app to Azure Web App - repgpt-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./server

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore
        working-directory: ./server

      - name: Publish app
        run: dotnet publish -c Release -o ./publish
        working-directory: ./server

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./server/publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C5B261C1FF994576A7FE0BB102F6974E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F4FC477013CF476B958A521F5C37A0DE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D8096EA31B824749AF57B3A9672317E8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "repgpt-api"
          slot-name: "Production"
          package: ./publish
